# Generated by Django 5.1.7 on 2025-04-09 04:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bdounibank', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('maximum_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('minimum_term', models.IntegerField()),
                ('maximum_term', models.IntegerField()),
                ('processing_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('term_months', models.IntegerField()),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('paid', 'Paid'), ('defaulted', 'Defaulted'), ('closed', 'Closed')], default='pending', max_length=10)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('disbursal_date', models.DateTimeField(blank=True, null=True)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('final_payment_date', models.DateField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
                ('linked_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_loans', to='bdounibank.bankaccount')),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='loans.loantype')),
            ],
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('principal_component', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_component', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.transaction')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
    ]
